[package]
name = "lunes-wasm"
version = "0.1.0"
edition = "2021"
description = "Library for communication with nodes in mainnet or testnet of the lunes-blockchain network Allows the automation of sending assets, issue end reissue tokens, leasing, registry, and create new wallet."
authors = ["Lunes Platform <development@lunes.io>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["cryptocurrency","lunes","blockchain"]

[dependencies]
