image: lunesplatform/lunesrs:amd

stages:
    - build
    - test
    - deploy

BuildRelease:
    stage: build
    script:
        - cargo build --release
    artifacts:
        expose_as: "new release lunesrs"
        when: always
        paths:
            - target/release/

BuildWebAssembly:
    stage: build
    script:
        - wasm-pack build --target nodejs
    artifacts:
        expose_as: "web assembly lunesrs"
        when: always
        paths:
            - pkg/

TestRelease:
    stage: test
    script:
        - cargo test
    needs:
        - job: "BuildRelease"

TestWebAssembly:
    stage: test
    script:
        - wasm-pack test --node
    needs:
        - job: "BuildWebAssembly"

# DeployNPM:
#     stage: deploy
#     script:
#         - wasm-pack login -u $USR_NPM -p $PWD_NPM
#         - wasm-pack publish
#     needs:
#         - job: "BuildWebAssembly"
#         - job: "TestWebAssembly"
#         - job: "BuildRelease"
#         - job: "TestRelease"