image: rust

stages:
    - test
    - build

BuildRelease:
    stage: build
    script:
        - cargo build --release
    artifacts:
        name: "lunesrs" 
        expose_as: "pre-release"
        when: always
        paths:
            - target/release/


BuildPackage:
    before_script:
        - cargo install wasm-pack
    stage: build
    script:
        - wasm-pack build --target nodejs
    artifacts:
        name: "lunesjs" 
        expose_as: "pre-release"
        when: always
        paths:
            - pkg/

CreateReportTests:
    stage: test
    script:
        - cargo test
    # artifacts:
    #     when: always
    #     reports:
    #         junit: report.xml

TestNodeJsWebAssembly:
    before_script:
        - cargo install wasm-pack
    stage: test
    script:
        - wasm-pack test --node


# DeployPackage:
#     before_script:
#         - cargo install wasm-pack
#     stage: deploy
#     script:
#         - cargo install wasm-pack
#         - wasm-pack login -u $USR_NPM -p $PWD_NPM
#         - wasm-pack build --target nodejs
#         - wasm-pack publish